name: hawalik
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.4
  lucide_icons: ^0.257.0
  firebase_core: ^3.11.0
  cloud_firestore: ^5.6.3
  flutter_cube: ^0.1.1
  firebase_auth: ^5.5.0
  google_maps_flutter: ^2.10.0
  location: ^8.0.0
  geolocator: ^13.0.2
  permission_handler: ^11.3.1
  http: ^1.3.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/icons/

  fonts:
    - family: Cairo
      fonts:
        - asset: lib/assets/fonts/Amiri-Regular.ttf
          weight: 700
